### ISSUE TITLE
Why swipe was removed from BottomTabNavigator?

### ISSUE THREAD

**Issue by greenais** [react-navigation/react-navigation-material-bottom-tabs#17]
It's breaking change for some apps and, surely, it could be workarounded in a hacky way by using createMaterialTopTabNavigator and setting tabBarPosition: 'bottom', but I'm just curious:
what was the reason for removing swipe? 

I'm asking in order to understand what is the strategy and what to expect in future releases.

**Comment by balthazar** [comment]
Would like to know aswell :)

**Comment by balthazar** [comment]
I think the reason was it never was there. `createMaterialTopTabNavigator` main feature is to allow to lazy load components tabs, and I don't think it can be done if the horizontal swapping is enabled.

**Comment by satya164** [comment]
This is a completely different package (material bottom tabs) and your issue is irrelevant to this package. Your issue belongs to the `react-navigation-tabs` repo. But since you have opened the issue, I'll just answer it here anyway:

Most of the design guidelines discourage swipe on bottom tabs. I have never seen swipeable tabs for the bottom tabs, so it suffices to say it's extremely uncommon and users don't expect it. Removing it also simplified a lot of code which makes maintaining it easier as well as allowed us to add features such as lazy loading and resource saving which will never work well with swipeable tabs. That's why it was removed.

You shouldn't be adding a swipe gesture for bottom tabs if you want to provide a consistent UX. Tough, you can still build swipeable bottom tabs using the `tabBarPosition` prop though. It's in no way hacky, there's an officially supported prop, why would it be hacky?

Regarding breaking changes, `react-navigation-tabs` is a completely new package. The API is similar, but not the same. It's not guaranteed to be a straightforward migration. That's why React Navigation still exposes methods for the previous API which you can use if you're not ready to migrate.
